/* Generated By:JavaCC: Do not edit this line. JaggerConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JaggerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int TYPE = 6;
  /** RegularExpression Id. */
  int EOL = 7;
  /** RegularExpression Id. */
  int IN = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int LET = 10;
  /** RegularExpression Id. */
  int VARIABLE = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int THEN = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int TO = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int LPAR = 20;
  /** RegularExpression Id. */
  int RPAR = 21;
  /** RegularExpression Id. */
  int COPEN = 22;
  /** RegularExpression Id. */
  int CEND = 23;
  /** RegularExpression Id. */
  int EQ = 24;
  /** RegularExpression Id. */
  int ENDL = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int COLON = 27;
  /** RegularExpression Id. */
  int ID = 28;
  /** RegularExpression Id. */
  int STRING = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "<TYPE>",
    "\"\\n\"",
    "\"in\"",
    "\"end\"",
    "\"let\"",
    "\"var\"",
    "\"print\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"to\"",
    "\"do\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "<ID>",
    "<STRING>",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
